name: software-env
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.10.0
  - torchvision=0.11.1
  - pyqt=5.15.4
  - opencv=4.5.3
  - pillow=8.3.1
  - numpy=1.21.2
  - pandas=1.3.3
  - pip
  - pip:
    - pyinstaller==4.5.1